version: "3.8"

services:
  # flask_app:
  #   build: .
  #   container_name: flask_app
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - FLASK_ENV=production
  #   depends_on:
  #     - redis
  #   networks:
  #     - app_network

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
